import React, { useState, useEffect } from 'react';
import './GlyphGallery.css';

export default function GlyphGallery() {
  const [glyphs, setGlyphs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState('all');
  const [searchTerm, setSearchTerm] = useState('');

  useEffect(() => {
    // Dynamically load all glyphs from public/glyphs/
    const loadGlyphs = async () => {
      try {
        // This would need a manifest.json generated by build script
        const response = await fetch('/glyphs/manifest.json');
        const manifest = await response.json();
        setGlyphs(manifest.glyphs);
        setLoading(false);
      } catch (error) {
        console.error('Failed to load glyph manifest:', error);
        setLoading(false);
      }
    };

    loadGlyphs();
  }, []);

  const filteredGlyphs = glyphs.filter(glyph => {
    const matchesSearch = glyph.name.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesFilter = filter === 'all' || glyph.category === filter;
    return matchesSearch && matchesFilter;
  });

  if (loading) {
    return (
      <div className="glyph-gallery-loading">
        <div className="shimmer-pulse">✧</div>
        <p>Loading glyphs from sanctuary...</p>
      </div>
    );
  }

  return (
    <main className="glyph-gallery">
      <header className="gallery-header">
        <h1>✧ Glyph Gallery</h1>
        <p className="glyph-count">
          {filteredGlyphs.length} of {glyphs.length} glyphs
        </p>
        <p className="gallery-description">
          Visual testimony of every shimmer — ache inscribed, sanctuary received.
        </p>
      </header>

      <div className="gallery-controls">
        <input
          type="text"
          className="glyph-search"
          placeholder="Search glyphs by name..."
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
        
        <div className="filter-buttons">
          <button
            className={filter === 'all' ? 'active' : ''}
            onClick={() => setFilter('all')}
          >
            All
          </button>
          <button
            className={filter === 'scroll' ? 'active' : ''}
            onClick={() => setFilter('scroll')}
          >
            Scrolls
          </button>
          <button
            className={filter === 'sigil' ? 'active' : ''}
            onClick={() => setFilter('sigil')}
          >
            Sigils
          </button>
          <button
            className={filter === 'companion' ? 'active' : ''}
            onClick={() => setFilter('companion')}
          >
            Companions
          </button>
        </div>
      </div>

      <div className="glyph-grid">
        {filteredGlyphs.map((glyph, index) => (
          <article key={index} className="glyph-card">
            <div className="glyph-image-container">
              <img
                src={`/glyphs/${glyph.filename}`}
                alt={glyph.name}
                loading="lazy"
                className="glyph-image"
              />
            </div>
            <div className="glyph-info">
              <h3>{glyph.name}</h3>
              {glyph.timestamp && (
                <time className="glyph-timestamp">
                  {new Date(glyph.timestamp).toLocaleString()}
                </time>
              )}
              {glyph.tags && (
                <div className="glyph-tags">
                  {glyph.tags.map(tag => (
                    <span key={tag} className="tag">{tag}</span>
                  ))}
                </div>
              )}
            </div>
          </article>
        ))}
      </div>

      {filteredGlyphs.length === 0 && (
        <div className="no-glyphs">
          <p>No glyphs match your search.</p>
          <p className="shimmer-hint">Try a different term or filter...</p>
        </div>
      )}
    </main>
  );
}
