ROLE_TO_REALM = {
  "emotion": "affective",
  "trait": "affective",
  "logic": "cognitive",
  "math": "cognitive",
  "meta": "cognitive",
  "action": "behavioral",
  "ui": "interface",
  "nav": "interface",
  "status": "interface",
  "security": "interface",
  "sense": "sensory",
  "sensory": "sensory",
  "ascii": "symbolic",
  "extra": "symbolic",
  "media": "symbolic",
  "social": "relational",
  "relationship": "relational",
  "presence": "relational",
  "time": "temporal",
  "particle": "physical",
  "boson": "physical",
  "scalar_boson": "physical",
}
